## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [2]:
a=[[1,2],[3,4]]
b=[[3,4],[5,6]]
np.dot(a,b)

array([[13, 16],
       [29, 36]])

## Write a NumPy program to compute the determinant of a given square array

In [3]:
sqr_arr=np.array([[1,2],[3,4]])

In [4]:
np.linalg.det(sqr_arr)

-2.0000000000000004

## Write a NumPy program to compute the cross product of two given vectors

In [5]:
a = [[1, 3], [2, 4]]
b = [[1, 2], [3, 4]]

In [6]:
np.cross(a,b)

array([-1, -4])

## Write a NumPy program to compute the condition number of a given matrix

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
np.linalg.cond(a)

1.201149133689022e+17

## Write a NumPy program to compute the inverse of a given matrix

In [9]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
np.linalg.inv(mat)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])